import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger("loom.integrations.ci_bot")

BRANCH_PREFIX = "loom/fix"
EVIDENCE_BUNDLE_PATH = "/api/v1/runs/{run_id}/evidence"


class CIBotProvider(str, Enum):
    GITHUB = "github"
    GITLAB = "gitlab"


class CIBotEvent(str, Enum):
    ISSUE_OPENED = "issue.opened"
    ISSUE_LABELED = "issue.labeled"
    ISSUE_COMMENTED = "issue.commented"
    PR_OPENED = "pr.opened"
    PR_MERGED = "pr.merged"
    PR_CLOSED = "pr.closed"
    CHECK_SUITE_COMPLETED = "check_suite.completed"
    PUSH = "push"


class PullRequestTemplate(str, Enum):
    STANDARD = "standard"
    MINIMAL = "minimal"
    HOTFIX = "hotfix"


@dataclass
class CIBotConfig:
    provider: CIBotProvider
    org_id: str
    repo_full_name: str
    api_base_url: str
    install_token_ref: str = ""
    auto_triage_labels: List[str] = field(default_factory=lambda: ["loom:auto-fix"])
    draft_pr_by_default: bool = True
    verification_branch_prefix: str = BRANCH_PREFIX
    false_trigger_rate_threshold: float = 0.01
    max_open_prs: int = 5
    enabled: bool = True


@dataclass
class PullRequestTemplateData:
    run_id: str
    issue_title: str
    issue_number: int
    branch_name: str
    patch_diff: str
    evidence_bundle_url: str
    confidence_score: float
    verification_passed: bool
    cost_usd: float
    files_touched: int
    model_used: str


class CIBot:
    def __init__(
        self,
        config: CIBotConfig,
        api_client: Optional[Any] = None,
        on_event: Optional[Callable[[CIBotEvent, Dict[str, Any]], None]] = None,
    ):
        self.config = config
        self._api = api_client
        self._on_event = on_event
        self._event_counter: Dict[str, int] = {}
        self._false_trigger_count: int = 0
        self._total_triggers: int = 0

    def _track_event(self, event_type: CIBotEvent) -> None:
        self._event_counter[event_type.value] = self._event_counter.get(event_type.value, 0) + 1

    def _build_pr_body(self, template: PullRequestTemplate, data: PullRequestTemplateData) -> str:
        evidence_link = self.config.api_base_url.rstrip("/") + EVIDENCE_BUNDLE_PATH.format(run_id=data.run_id)
        status_icon = "✓" if data.verification_passed else "✗"
        base = [
            f"## Loom Automated Fix — {data.issue_title}",
            "",
            "| Field | Value |",
            "|---|---|",
            f"| **Confidence** | {data.confidence_score:.2%} |",
            f"| **Verification** | {status_icon} {'Passed' if data.verification_passed else 'Failed'} |",
            f"| **Files Touched** | {data.files_touched} |",
            f"| **Model** | {data.model_used} |",
            f"| **Cost** | ${data.cost_usd:.4f} |",
            f"| **Evidence Bundle** | [View Full Evidence]({evidence_link}) |",
            "",
            "---",
            "",
            "### ⚠️ Review Checklist",
            "",
            "- [ ] Verify the reproduction test passes on the patched branch",
            "- [ ] Confirm the fix does not introduce regressions",
            "- [ ] Review sensitive-path touches (auth, billing, migrations)",
            "- [ ] The evidence bundle is hash-chained and tamper-evident",
            "",
            f"> This PR was auto-generated by Loom CI Bot. Run ID: `{data.run_id}`",
            f"> Auto-merge threshold: {'enabled' if data.verification_passed and data.confidence_score >= 0.95 else 'requires review'}",
        ]
        if template == PullRequestTemplate.MINIMAL:
            return "\n".join(base[:4] + base[-3:])
        if template == PullRequestTemplate.HOTFIX:
            return "\n".join(base[:5] + ["", "**⚠️ HOTFIX — Expedited Review Requested**", ""] + base[-3:])
        return "\n".join(base)

    def should_triage_issue(self, issue_title: str, issue_labels: List[str], issue_body: str = "") -> bool:
        if not self.config.enabled:
            return False
        if any(label in self.config.auto_triage_labels for label in issue_labels):
            return True
        triage_keywords = ["bug", "fix", "error", "broken", "regression", "crash", "security", "vulnerability"]
        title_lower = issue_title.lower()
        return any(kw in title_lower for kw in triage_keywords)

    def _sanitize_branch_name(self, issue_title: str, issue_number: int) -> str:
        clean = "".join(c if c.isalnum() or c in "-_" else "-" for c in issue_title.lower())
        clean = clean[:40].strip("-")
        return f"{self.config.verification_branch_prefix}/{issue_number}-{clean}"

    def generate_pr_template_data(
        self,
        run_id: str,
        issue_title: str,
        issue_number: int,
        patch_diff: str,
        confidence_score: float,
        verification_passed: bool,
        cost_usd: float = 0.0,
        files_touched: int = 0,
        model_used: str = "unknown",
    ) -> PullRequestTemplateData:
        branch = self._sanitize_branch_name(issue_title, issue_number)
        return PullRequestTemplateData(
            run_id=run_id,
            issue_title=issue_title,
            issue_number=issue_number,
            branch_name=branch,
            patch_diff=patch_diff,
            evidence_bundle_url=self.config.api_base_url.rstrip("/") + EVIDENCE_BUNDLE_PATH.format(run_id=run_id),
            confidence_score=confidence_score,
            verification_passed=verification_passed,
            cost_usd=cost_usd,
            files_touched=files_touched,
            model_used=model_used,
        )

    def prepare_pr(
        self,
        data: PullRequestTemplateData,
        template: PullRequestTemplate = PullRequestTemplate.STANDARD,
    ) -> Dict[str, Any]:
        if not self.config.enabled:
            return {"action": "skipped", "reason": "bot_disabled"}
        current_count = self._event_counter.get("pr.opened", 0)
        if current_count >= self.config.max_open_prs:
            return {"action": "skipped", "reason": "max_open_prs_exceeded", "limit": self.config.max_open_prs}
        body = self._build_pr_body(template, data)
        self._track_event(CIBotEvent.PR_OPENED)
        return {
            "action": "prepared",
            "provider": self.config.provider.value,
            "repo": self.config.repo_full_name,
            "branch": data.branch_name,
            "base_branch": "main",
            "title": f"[Loom] Fix: {data.issue_title}",
            "body": body,
            "draft": self.config.draft_pr_by_default,
            "labels": ["loom:automated", "loom:needs-review"],
            "issue_reference": f"#{data.issue_number}",
            "evidence_bundle_url": data.evidence_bundle_url,
            "run_id": data.run_id,
        }

    def _compute_false_trigger_rate(self) -> float:
        if self._total_triggers == 0:
            return 0.0
        return self._false_trigger_count / self._total_triggers

    def record_trigger_result(self, was_correct_fix: bool) -> None:
        self._total_triggers += 1
        if not was_correct_fix:
            self._false_trigger_count += 1
        rate = self._compute_false_trigger_rate()
        if rate > self.config.false_trigger_rate_threshold:
            logger.warning(
                "False trigger rate %.2f%% exceeds threshold %.2f%% — bot may need recalibration",
                rate * 100,
                self.config.false_trigger_rate_threshold * 100,
            )

    @property
    def false_trigger_rate(self) -> float:
        return self._compute_false_trigger_rate()

    @property
    def event_stats(self) -> Dict[str, int]:
        return dict(self._event_counter)

    def reset_stats(self) -> None:
        self._event_counter.clear()
        self._false_trigger_count = 0
        self._total_triggers = 0

    def build_verification_branch_name(self, issue_title: str, issue_number: int) -> str:
        return self._sanitize_branch_name(issue_title, issue_number)

    def build_commit_message(self, run_id: str, issue_title: str, confidence_score: float) -> str:
        return f"fix: {issue_title}\n\nLoom automated fix (run: {run_id}, confidence: {confidence_score:.2%})"

    def serialize(self) -> Dict[str, Any]:
        return {
            "provider": self.config.provider.value,
            "repo": self.config.repo_full_name,
            "enabled": self.config.enabled,
            "draft_prs": self.config.draft_pr_by_default,
            "max_open_prs": self.config.max_open_prs,
            "stats": self.event_stats,
            "false_trigger_rate": round(self.false_trigger_rate, 4),
        }


class GitHubCIBot:
    """Compatibility adapter around the current provider-neutral CIBot."""

    def __init__(self, config: Optional[CIBotConfig] = None):
        self._bot = config and CIBot(config) or CIBot(
            CIBotConfig(
                provider=CIBotProvider.GITHUB,
                org_id="default",
                repo_full_name="",
                api_base_url="",
            )
        )

    def prepare_pr(
        self,
        *,
        run_id: str,
        issue_title: str,
        issue_number: int,
        patch_diff: str,
        confidence_score: float,
        verification_passed: bool,
        cost_usd: float = 0.0,
        files_touched: int = 0,
        model_used: str = "unknown",
        template: str = "standard",
    ) -> Dict[str, Any]:
        try:
            template_value = PullRequestTemplate(template)
        except ValueError as exc:
            raise ValueError(f"Unsupported PR template: {template}") from exc
        data = self._bot.generate_pr_template_data(
            run_id=run_id,
            issue_title=issue_title,
            issue_number=issue_number,
            patch_diff=patch_diff,
            confidence_score=confidence_score,
            verification_passed=verification_passed,
            cost_usd=cost_usd,
            files_touched=files_touched,
            model_used=model_used,
        )
        return self._bot.prepare_pr(data, template_value)
