#!/usr/bin/env python3
"""Loom Real API Configuration & Validator Wizard.

Generates or updates root `.env` (FastAPI backend) and `web/.env.local` (Next.js dashboard),
validates LLM provider connectivity, and prints ready-to-use Vercel environment variables.
"""

from __future__ import annotations

import argparse
import os
import secrets
import sys
from pathlib import Path
from typing import Dict, List

REPO_ROOT = Path(__file__).resolve().parent.parent
WEB_DIR = REPO_ROOT / "web"
ENV_PATH = REPO_ROOT / ".env"
WEB_ENV_PATH = WEB_DIR / ".env.local"


def generate_secret(nbytes: int = 32) -> str:
    return secrets.token_urlsafe(nbytes)


def load_env_file(path: Path) -> Dict[str, str]:
    if not path.exists():
        return {}
    values: Dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            k, v = line.split("=", 1)
            values[k.strip()] = v.strip().strip("'\"")
    return values


def write_env_file(path: Path, values: Dict[str, str], header: str) -> None:
    lines = [f"# {header}", "# Auto-generated by scripts/configure_real_api.py", ""]
    for k, v in values.items():
        lines.append(f"{k}={v}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def check_llm_keys(env: Dict[str, str]) -> List[str]:
    active_keys = []
    for key in ["ANTHROPIC_API_KEY", "OPENAI_API_KEY", "GEMINI_API_KEY", "DEEPSEEK_API_KEY"]:
        val = env.get(key) or os.getenv(key)
        if val and not val.startswith("your-") and not val.startswith("replace-"):
            active_keys.append(key)
    return active_keys


def run_configuration(args: argparse.Namespace) -> int:
    existing_backend = load_env_file(ENV_PATH)
    existing_web = load_env_file(WEB_ENV_PATH)

    api_key = (
        args.api_key
        or existing_backend.get("API_KEY")
        or existing_web.get("API_KEY")
        or generate_secret(24)
    )
    dashboard_token = (
        args.dashboard_token
        or existing_backend.get("DASHBOARD_AUTH_TOKEN")
        or existing_web.get("DASHBOARD_AUTH_TOKEN")
        or generate_secret(16)
    )
    session_secret = (
        args.session_secret
        or existing_backend.get("DASHBOARD_SESSION_SECRET")
        or existing_web.get("DASHBOARD_SESSION_SECRET")
        or generate_secret(32)
    )

    anthropic_key = args.anthropic_key or existing_backend.get("ANTHROPIC_API_KEY", "")
    openai_key = args.openai_key or existing_backend.get("OPENAI_API_KEY", "")
    gemini_key = args.gemini_key or existing_backend.get("GEMINI_API_KEY", "")
    deepseek_key = args.deepseek_key or existing_backend.get("DEEPSEEK_API_KEY", "")

    backend_url = args.backend_url or existing_web.get("LOOM_API_URL", "http://127.0.0.1:8000")
    vercel_origin = args.vercel_origin or existing_web.get(
        "NEXT_PUBLIC_APP_ORIGIN", ""
    )

    backend_env = {
        "LOOM_ENV": "production" if args.production else "development",
        "DEV_MODE": "false" if args.production else "true",
        "API_KEY": api_key,
        "API_KEY_USER_ID": "admin_user",
        "API_KEY_ORG_ID": "default",
        "DASHBOARD_AUTH_TOKEN": dashboard_token,
        "ALLOWED_ORIGINS": f"http://localhost:3000,http://127.0.0.1:3000,{vercel_origin}",
        "ALLOWED_REPO_ROOTS": str(REPO_ROOT),
        "RATE_LIMIT_PER_MINUTE": "120",
        "LOOM_DB_PATH": str(REPO_ROOT / ".loom" / "memory.db"),
        "ANTHROPIC_API_KEY": anthropic_key,
        "OPENAI_API_KEY": openai_key,
        "GEMINI_API_KEY": gemini_key,
        "DEEPSEEK_API_KEY": deepseek_key,
        "MODEL_DEFAULT": args.default_model or "claude-3-7-sonnet-20250219",
    }

    web_env = {
        "LOOM_API_URL": backend_url,
        "API_KEY": api_key,
        "LOOM_API_KEY": api_key,
        "DASHBOARD_AUTH_TOKEN": dashboard_token,
        "DASHBOARD_SESSION_SECRET": session_secret,
        "NEXT_PUBLIC_APP_ORIGIN": vercel_origin,
    }

    if not args.check_only:
        write_env_file(ENV_PATH, backend_env, "Loom Backend Environment")
        write_env_file(WEB_ENV_PATH, web_env, "Loom Next.js Dashboard Environment")
        print(" Successfully wrote:")
        print(f"  - Backend configuration: {ENV_PATH}")
        print(f"  - Frontend configuration: {WEB_ENV_PATH}")
    else:
        print("🔎 Check-only mode: Files were not modified.")

    active_llms = check_llm_keys(backend_env)
    print("\n--- LLM Provider Status ---")
    if active_llms:
        for k in active_llms:
            print(f"  [ACTIVE] {k}")
    else:
        print("  ⚠️  No active LLM API keys configured yet.")
        print("  Set ANTHROPIC_API_KEY, OPENAI_API_KEY, GEMINI_API_KEY, or DEEPSEEK_API_KEY.")

    print("\n--- Credentials Summary ---")
    print(f"  Dashboard Token : {dashboard_token}")
    print(f"  Backend API Key : {api_key}")
    print(f"  Backend URL     : {backend_url}")

    print("\n--- Vercel Environment Variables (Copy & Paste to Vercel Settings) ---")
    print(f"DASHBOARD_AUTH_TOKEN={dashboard_token}")
    print(f"API_KEY={api_key}")
    print(f"LOOM_API_KEY={api_key}")
    print(f"LOOM_API_URL={backend_url}")
    print(f"DASHBOARD_SESSION_SECRET={session_secret}")
    print(f"NEXT_PUBLIC_APP_ORIGIN={vercel_origin}")
    print("----------------------------------------------------------------------\n")

    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Configure real API keys for Loom.")
    parser.add_argument("--api-key", help="Shared backend API Key")
    parser.add_argument("--dashboard-token", help="Dashboard Login Token")
    parser.add_argument("--session-secret", help="Dashboard Session Secret")
    parser.add_argument("--anthropic-key", help="Anthropic API Key (sk-ant-...)")
    parser.add_argument("--openai-key", help="OpenAI API Key (sk-...)")
    parser.add_argument("--gemini-key", help="Google Gemini API Key")
    parser.add_argument("--deepseek-key", help="DeepSeek API Key")
    parser.add_argument("--backend-url", help="URL of hosted Loom backend")
    parser.add_argument("--vercel-origin", help="Origin of Vercel dashboard")
    parser.add_argument("--default-model", help="Default model name")
    parser.add_argument("--production", action="store_true", help="Set LOOM_ENV=production")
    parser.add_argument("--check-only", action="store_true", help="Inspect configuration without modifying files")

    args = parser.parse_args()
    return run_configuration(args)


if __name__ == "__main__":
    sys.exit(main())
